"""File placement for `waxseal install <target>`.

The written shims contain no logic — they import from waxseal.integrations.*,
so `pip install -U waxseal` updates hook behavior without re-running install.
Hosts only discover hooks in their own config directories, and Python wheels
cannot run post-install steps (by design), which is why this command exists
at all.

Never touches any audit log; never overwrites an operator's differing file
without --force (install reports and stops, the way verify reports and never
repairs).
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

TARGETS = (
    "hermes",
    "hermes-gateway",
    "claude-code",
    "codex",
    "cursor",
    "langchain",
    "crewai",
    "openai-agents",
    "openclaw",
)

_STDIN_HOOK_SHIM = '''#!/usr/bin/env python3
"""waxseal-audit hook shim — the logic lives in waxseal.integrations.{module}.

Written by `waxseal install {target}`. Upgrade behavior with
`pip install -U waxseal`; do not edit this file.
"""
import sys

try:
    from waxseal.integrations.{module} import main
except Exception as e:
    # Exit 0 even here: a missing waxseal must never veto the host's work,
    # and the degradation is labelled on stderr, never silent.
    print(f"[waxseal-audit] waxseal not importable (entry dropped): {{e}}", file=sys.stderr)
    sys.exit(0)

sys.exit(main())
'''

_HERMES_PLUGIN_SHIM = '''"""waxseal-audit hermes plugin shim — the logic lives in
waxseal.integrations.hermes. Written by `waxseal install hermes`; upgrade
with `pip install -U waxseal`, do not edit."""

from waxseal.integrations.hermes import (  # noqa: F401
    on_post_tool_call,
    on_pre_tool_call,
    register,
)
'''

_HERMES_GATEWAY_SHIM = '''"""waxseal-audit hermes gateway hook shim — the logic lives in
waxseal.integrations.hermes_gateway. Written by `waxseal install
hermes-gateway`; upgrade with `pip install -U waxseal`, do not edit."""

from waxseal.integrations.hermes_gateway import handle  # noqa: F401
'''

# Targets that attach in the user's own code: nothing to place on disk.
_LIBRARY_USAGE = {
    "langchain": (
        "from waxseal.integrations.langchain import WaxsealCallbackHandler\n"
        'agent.invoke(input, config={"callbacks": [WaxsealCallbackHandler(trail_path)]})'
    ),
    "crewai": (
        "from waxseal.integrations.crewai import WaxsealEventListener\n"
        "audit = WaxsealEventListener(trail_path)  # keep the reference alive"
    ),
    "openai-agents": (
        "from waxseal.integrations.openai_agents import WaxsealRunHooks\n"
        'result = await Runner.run(agent, "input", hooks=WaxsealRunHooks(trail_path))'
    ),
}

# Targets that run on a timer rather than inside the host: nothing to place on
# disk either, but the guidance is a schedule, not an import.
_RUNNER_USAGE = {
    "openclaw": (
        "OpenClaw keeps its own audit ledger but prunes it (30 days, 100k rows) and\n"
        "hashes no row. Chain it from a timer — nothing runs on the agent's path:\n\n"
        "  */5 * * * * python -m waxseal.integrations.openclaw\n\n"
        "Trail: $OPENCLAW_HOME/audit/trail.jsonl (default ~/.openclaw/audit/trail.jsonl).\n"
        "Verify anytime: waxseal verify ~/.openclaw/audit/trail.jsonl\n"
        "Requires the `openclaw` CLI on PATH and a running gateway to answer it."
    ),
}

_HOOKS_JSON_EVENTS = {
    "claude-code": ("PreToolUse", "PostToolUse", "UserPromptSubmit"),
    "codex": ("PreToolUse", "PostToolUse", "UserPromptSubmit"),
}


def _note_home_unused(target: str, home: Path | None) -> None:
    if home is None:
        return
    print(
        f"note: --home has no effect for {target} "
        "(nothing is installed to a home directory)",
        file=sys.stderr,
    )


def _default_home(target: str) -> Path:
    if target.startswith("hermes"):
        env = os.environ.get("HERMES_HOME")
        return Path(env) if env else Path.home() / ".hermes"
    host_dir = {"claude-code": ".claude", "codex": ".codex", "cursor": ".cursor"}[target]
    return Path.home() / host_dir


def _write(path: Path, content: str, force: bool) -> bool:
    # utf-8 + newline="" on both sides: the locale default (cp1252 on Windows)
    # wrote these shims' em dashes as 0x97, and Python source must be UTF-8 —
    # the installed hermes plugin failed to import with a SyntaxError
    # (found running `waxseal install hermes` 0.1.0 on Windows, 2026-08-21).
    if path.exists():
        # No newline= here: Path.read_text only grew it in 3.13, and universal
        # newlines already fold any legacy CRLF copy back to the \n content.
        if path.read_text(encoding="utf-8") == content:
            print(f"unchanged: {path}")
            return True
        if not force:
            print(f"REFUSED: {path} exists with different content (rerun with --force)")
            return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="")
    print(f"wrote: {path}")
    return True


def install(target: str, home: Path | None, force: bool) -> int:
    if target in _LIBRARY_USAGE:
        # These returns run before `home` is ever read, so an explicit --home
        # was silently ignored — the same unlabelled-no-op class the CLI's
        # remote --anchors note exists for (CLAUDE.md rule 6).
        _note_home_unused(target, home)
        print(f"{target} attaches in your own code — nothing to install:\n")
        print(_LIBRARY_USAGE[target])
        return 0

    if target in _RUNNER_USAGE:
        _note_home_unused(target, home)
        print(f"{target} is ingested on a schedule — nothing to install:\n")
        print(_RUNNER_USAGE[target])
        return 0

    home = home if home is not None else _default_home(target)

    if target == "hermes":
        from waxseal.integrations.hermes import PLUGIN_MANIFEST

        plugin_dir = home / "plugins" / "waxseal-audit"
        ok = _write(plugin_dir / "plugin.yaml", PLUGIN_MANIFEST, force)
        ok = _write(plugin_dir / "__init__.py", _HERMES_PLUGIN_SHIM, force) and ok
        if ok:
            # Standalone plugins are opt-in; forgetting this = silent no-audit.
            print("now run: hermes plugins enable waxseal-audit")
        return 0 if ok else 1

    if target == "hermes-gateway":
        from waxseal.integrations.hermes_gateway import HOOK_MANIFEST

        hook_dir = home / "hooks" / "waxseal-audit"
        ok = _write(hook_dir / "HOOK.yaml", HOOK_MANIFEST, force)
        ok = _write(hook_dir / "handler.py", _HERMES_GATEWAY_SHIM, force) and ok
        if ok:
            print("the gateway discovers it on next startup (gateway process only)")
        return 0 if ok else 1

    # stdin/stdout hook hosts: claude-code, codex, cursor
    module = target.replace("-", "_")
    shim_path = home / "hooks" / "waxseal_hook.py"
    if not _write(shim_path, _STDIN_HOOK_SHIM.format(module=module, target=target), force):
        return 1
    print(f"\nadd to {_config_name(target)}:\n")
    print(_config_snippet(target, shim_path))
    return 0


def _config_name(target: str) -> str:
    return {
        "claude-code": "~/.claude/settings.json (or a project's .claude/settings.json)",
        "codex": "~/.codex/hooks.json",
        "cursor": "~/.cursor/hooks.json (or a project's .cursor/hooks.json)",
    }[target]


def _config_snippet(target: str, shim: Path) -> str:
    cmd = f"python3 {shim}"
    if target == "cursor":
        events = (
            "beforeShellExecution", "afterShellExecution", "beforeMCPExecution",
            "afterFileEdit", "beforeSubmitPrompt", "stop",
        )
        rows = ",\n".join(f'    "{e}": [{{ "command": "{cmd}" }}]' for e in events)
        return '{\n  "version": 1,\n  "hooks": {\n' + rows + "\n  }\n}"
    rows = ",\n".join(
        f'    "{e}": [{{ "hooks": [{{ "type": "command", "command": "{cmd}" }}] }}]'
        for e in _HOOKS_JSON_EVENTS[target]
    )
    return '{\n  "hooks": {\n' + rows + "\n  }\n}"
