"""File placement for `waxseal install <target>`.

The written shims contain no logic. They import from waxseal.integrations.*,
so `pip install -U waxseal` updates hook behavior without re-running install.
Hosts only discover hooks in their own config directories, and Python wheels
cannot run post-install steps (by design), which is why this command exists
at all.

Never touches any audit log; never overwrites an operator's differing file
without --force (install reports and stops, the way verify reports and never
repairs).
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

from waxseal.integrations._trail import home_base

TARGETS = (
    "hermes",
    "hermes-gateway",
    "claude-code",
    "codex",
    "cursor",
    "langchain",
    "crewai",
    "openai-agents",
    "openclaw",
    "agt",
)

_STDIN_HOOK_SHIM = '''#!/usr/bin/env python3
"""waxseal-audit hook shim — the logic lives in waxseal.integrations.{module}.

Written by `waxseal install {target}`. Upgrade behavior with
`pip install -U waxseal`; do not edit this file.
"""
import sys

try:
    from waxseal.integrations.{module} import main
except Exception as e:
    # Exit 0 even here: a missing waxseal must never veto the host's work,
    # and the degradation is labelled on stderr, never silent.
    print(f"[waxseal-audit] waxseal not importable (entry dropped): {{e}}", file=sys.stderr)
    sys.exit(0)

sys.exit(main())
'''

_HERMES_PLUGIN_SHIM = '''"""waxseal-audit hermes plugin shim — the logic lives in
waxseal.integrations.hermes. Written by `waxseal install hermes`; upgrade
with `pip install -U waxseal`, do not edit."""

from waxseal.integrations.hermes import (  # noqa: F401
    on_post_tool_call,
    on_pre_tool_call,
    register,
)
'''

_HERMES_GATEWAY_SHIM = '''"""waxseal-audit hermes gateway hook shim — the logic lives in
waxseal.integrations.hermes_gateway. Written by `waxseal install
hermes-gateway`; upgrade with `pip install -U waxseal`, do not edit."""

from waxseal.integrations.hermes_gateway import handle  # noqa: F401
'''

# Targets that attach in the user's own code: nothing to place on disk.
_LIBRARY_USAGE = {
    "langchain": (
        "from waxseal.integrations.langchain import WaxsealCallbackHandler\n"
        'agent.invoke(input, config={"callbacks": [WaxsealCallbackHandler(trail_path)]})'
    ),
    "crewai": (
        "from waxseal.integrations.crewai import WaxsealEventListener\n"
        "audit = WaxsealEventListener(trail_path)  # keep the reference alive"
    ),
    "openai-agents": (
        "from waxseal.integrations.openai_agents import WaxsealRunHooks\n"
        'result = await Runner.run(agent, "input", hooks=WaxsealRunHooks(trail_path))'
    ),
    "agt": (
        "from agentmesh.governance import AuditLog as AGTAuditLog\n"
        "from waxseal.integrations.agt import WaxsealAuditSink\n\n"
        "audit = AGTAuditLog(sink=WaxsealAuditSink(trail_path))\n"
        'audit.log(event_type="policy_evaluation", agent_did="did:web:agent-1",\n'
        '          action="read_file", outcome="allow", policy_decision="allow")\n\n'
        "Note: govern()'s own wrapper builds its OWN AuditLog with no way to\n"
        "attach a sink (agent-governance-toolkit-core 4.1.0 and 5.0.0, both\n"
        "read — a confirmed upstream gap, not a waxseal limitation). Call\n"
        "AGTAuditLog(sink=...) yourself at your governance checkpoints, or\n"
        "reach into `governed._audit = AGTAuditLog(sink=...)` post-construction\n"
        "(a private attribute; there is no public setter upstream)."
    ),
}

# Targets that run on a timer rather than inside the host: nothing to place on
# disk either, but the guidance is a schedule, not an import.
_RUNNER_USAGE = {
    "openclaw": (
        "OpenClaw keeps its own audit ledger but prunes it (30 days, 100k rows) and\n"
        "hashes no row. Chain it from a timer — nothing runs on the agent's path:\n\n"
        f"  */5 * * * * {sys.executable} -m waxseal.integrations.openclaw\n\n"
        "Trail: $OPENCLAW_HOME/audit/trail.jsonl (default ~/.openclaw/audit/trail.jsonl).\n"
        "Verify anytime: waxseal verify ~/.openclaw/audit/trail.jsonl\n"
        "Requires the `openclaw` CLI on PATH and a running gateway to answer it."
    ),
}

_HOOKS_JSON_EVENTS = {
    "claude-code": ("PreToolUse", "PostToolUse", "UserPromptSubmit"),
    "codex": ("PreToolUse", "PostToolUse", "UserPromptSubmit"),
}


def _note_home_unused(target: str, home: Path | None) -> None:
    if home is None:
        return
    print(
        f"note: --home has no effect for {target} "
        "(nothing is installed to a home directory)",
        file=sys.stderr,
    )


def _default_home(target: str) -> Path:
    """Where a target's shim files go when `--home` names nothing.

    `home_base()`, not ``Path.home()``: install placement has to agree with
    the trail resolvers, which all read `HOME` first (the ntpath split is
    documented on `home_base` itself). Placing a shim under the USERPROFILE
    profile while the host that loads it was launched with `HOME` set means
    the shim is never loaded and there is no trail at all — no short chain to
    misread, no evidence of any kind (waxseal-fg4.19).
    """
    if target.startswith("hermes"):
        env = os.environ.get("HERMES_HOME")
        return Path(env) if env else home_base() / ".hermes"
    host_dir = {"claude-code": ".claude", "codex": ".codex", "cursor": ".cursor"}[target]
    return home_base() / host_dir


def _write(path: Path, content: str, force: bool) -> bool:
    # utf-8 + newline="" on both sides: the locale default (cp1252 on Windows)
    # wrote these shims' em dashes as 0x97, and Python source must be UTF-8, so
    # the installed hermes plugin failed to import with a SyntaxError
    # (found running `waxseal install hermes` 0.1.0 on Windows, 2026-08-21).
    if path.exists():
        # No newline= here: Path.read_text only grew it in 3.13, and universal
        # newlines already fold any legacy CRLF copy back to the \n content.
        if path.read_text(encoding="utf-8") == content:
            print(f"unchanged: {path}")
            return True
        if not force:
            print(f"REFUSED: {path} exists with different content (rerun with --force)")
            return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="")
    print(f"wrote: {path}")
    return True


def install(target: str, home: Path | None, force: bool) -> int:
    if target in _LIBRARY_USAGE:
        # These returns run before `home` is ever read, so an explicit --home
        # was silently ignored, the same unlabelled-no-op class the CLI's
        # remote --anchors note exists for (CLAUDE.md rule 6).
        _note_home_unused(target, home)
        print(f"{target} attaches in your own code — nothing to install:\n")
        print(_LIBRARY_USAGE[target])
        return 0

    if target in _RUNNER_USAGE:
        _note_home_unused(target, home)
        print(f"{target} is ingested on a schedule — nothing to install:\n")
        print(_RUNNER_USAGE[target])
        return 0

    home = home if home is not None else _default_home(target)

    if target == "hermes":
        from waxseal.integrations.hermes import PLUGIN_MANIFEST

        plugin_dir = home / "plugins" / "waxseal-audit"
        ok = _write(plugin_dir / "plugin.yaml", PLUGIN_MANIFEST, force)
        ok = _write(plugin_dir / "__init__.py", _HERMES_PLUGIN_SHIM, force) and ok
        if ok:
            # Standalone plugins are opt-in; forgetting this = silent no-audit.
            print("now run: hermes plugins enable waxseal-audit")
        return 0 if ok else 1

    if target == "hermes-gateway":
        from waxseal.integrations.hermes_gateway import HOOK_MANIFEST

        hook_dir = home / "hooks" / "waxseal-audit"
        ok = _write(hook_dir / "HOOK.yaml", HOOK_MANIFEST, force)
        ok = _write(hook_dir / "handler.py", _HERMES_GATEWAY_SHIM, force) and ok
        if ok:
            print("the gateway discovers it on next startup (gateway process only)")
        return 0 if ok else 1

    # stdin/stdout hook hosts: claude-code, codex, cursor
    module = target.replace("-", "_")
    shim_path = home / "hooks" / "waxseal_hook.py"
    if not _write(shim_path, _STDIN_HOOK_SHIM.format(module=module, target=target), force):
        return 1
    print(f"\nadd to {_config_name(target)}:\n")
    print(_config_snippet(target, shim_path))
    return 0


def _config_name(target: str) -> str:
    return {
        "claude-code": "~/.claude/settings.json (or a project's .claude/settings.json)",
        "codex": "~/.codex/hooks.json",
        "cursor": "~/.cursor/hooks.json (or a project's .cursor/hooks.json)",
    }[target]


def _config_snippet(target: str, shim: Path) -> str:
    # sys.executable, never a bare `python3`: the interpreter on PATH is not
    # necessarily the one that has waxseal installed. When it is not, every hook
    # event is dropped with a label nobody reads and the trail stays empty while
    # the hooks look installed — which is exactly what happened on the
    # repository owner's machine (0.1.5 plan, Workstream D1). The interpreter
    # running `waxseal install` demonstrably has waxseal, so it is the one to
    # name. The shim keeps its `#!/usr/bin/env python3` shebang, which is a
    # fail-open the host may deliberately override.
    cmd = f"{sys.executable} {shim}"
    if target == "cursor":
        events = (
            "beforeShellExecution", "afterShellExecution", "beforeMCPExecution",
            "afterFileEdit", "beforeSubmitPrompt", "stop",
        )
        rows = ",\n".join(f'    "{e}": [{{ "command": "{cmd}" }}]' for e in events)
        return '{\n  "version": 1,\n  "hooks": {\n' + rows + "\n  }\n}"
    rows = ",\n".join(
        f'    "{e}": [{{ "hooks": [{{ "type": "command", "command": "{cmd}" }}] }}]'
        for e in _HOOKS_JSON_EVENTS[target]
    )
    return '{\n  "hooks": {\n' + rows + "\n  }\n}"
