// SPDX-License-Identifier: MIT
pragma solidity 0.8.36;

import {VectorTest} from "./Vm.sol";
import {AnchoringLiveness} from "../src/AnchoringLiveness.sol";
import {CheckpointCodec} from "../src/CheckpointCodec.sol";
import {Rfc9162} from "../src/Rfc9162.sol";

contract AnchoringLivenessTest is VectorTest {
    AnchoringLiveness internal alc;

    uint256 internal constant WRITER_KEY = 0xA11CE;
    bytes32 internal constant TRAIL = keccak256("waxseal-test-trail");
    uint64 internal constant DEADLINE = 3600;

    address internal writer;
    address internal stranger;

    function setUp() public {
        alc = new AnchoringLiveness();
        writer = vm.addr(WRITER_KEY);
        stranger = vm.addr(0xB0B);
        alc.registerTrail(TRAIL, writer, DEADLINE);
        vm.warp(1_800_000_000);
    }

    function _sign(uint256 key, uint64 seq, bytes32 entryHash, bytes32 root)
        internal
        pure
        returns (bytes memory)
    {
        bytes32 digest = CheckpointCodec.signingDigest(TRAIL, seq, entryHash, root);
        (uint8 v, bytes32 r, bytes32 s) = vm.sign(key, digest);
        return abi.encodePacked(r, s, v);
    }

    function _head(uint256 i)
        internal
        view
        returns (uint64 seq, bytes32 entryHash, bytes32 root, bytes32[] memory proof)
    {
        string memory json = _chunk("heads", 0);
        seq = uint64(vm.parseJsonUint(json, _at(i, "seq")));
        entryHash = vm.parseJsonBytes32(json, _at(i, "entryHash"));
        root = vm.parseJsonBytes32(json, _at(i, "root"));
        proof = vm.parseJsonBytes32Array(json, _at(i, "proofFromPrev"));
    }

    function _submitHead(uint256 i) internal returns (uint64 seq) {
        bytes32 entryHash;
        bytes32 root;
        bytes32[] memory proof;
        (seq, entryHash, root, proof) = _head(i);
        alc.submit(TRAIL, seq, entryHash, root, _sign(WRITER_KEY, seq, entryHash, root), proof);
    }

    /// @notice The honest sequence of anchored heads, each proving it extends
    ///         the last, against proofs generated by the Python side.
    function test_honestHeadSequenceAdvances() public {
        (uint256 count,) = _layout("heads");
        for (uint256 i = 0; i < count; i++) {
            uint64 seq = _submitHead(i);
            (uint64 seenSeq,,, uint64 blockTime) = alc.lastSeen(TRAIL);
            require(seenSeq == seq, "head did not advance");
            require(blockTime == uint64(block.timestamp), "block time not recorded");
            require(!alc.isDelinquent(TRAIL), "delinquent immediately after anchoring");
        }
    }

    /// @notice Anyone may relay a writer-SIGNED head.
    /// @dev The paper's "any party may submit". The signature is what keeps
    ///      that from becoming "any party may fake a live trail": a liveness
    ///      signal a stranger can turn green is worse than none, because it
    ///      reads as reassurance.
    function test_strangerMayRelayASignedHead() public {
        (uint64 seq, bytes32 entryHash, bytes32 root, bytes32[] memory proof) = _head(0);
        bytes memory sig = _sign(WRITER_KEY, seq, entryHash, root);
        (bool ok,) = address(alc)
            .call(
                abi.encodeCall(AnchoringLiveness.submit, (TRAIL, seq, entryHash, root, sig, proof))
            );
        require(ok, "a signed head was refused because of who relayed it");
    }

    function test_unsignedHeadRejected() public {
        (uint64 seq, bytes32 entryHash, bytes32 root, bytes32[] memory proof) = _head(0);
        bytes memory forged = _sign(0xB0B, seq, entryHash, root);
        (bool ok, bytes memory err) = address(alc)
            .call(
                abi.encodeCall(
                    AnchoringLiveness.submit, (TRAIL, seq, entryHash, root, forged, proof)
                )
            );
        require(!ok, "a stranger's signature was accepted");
        require(bytes4(err) == AnchoringLiveness.BadWriterSignature.selector, "wrong reason");
    }

    /// @notice A signature for one trail does not work on another.
    function test_signatureFromAnotherTrailRejected() public {
        bytes32 other = keccak256("some-other-trail");
        alc.registerTrail(other, writer, DEADLINE);
        (uint64 seq, bytes32 entryHash, bytes32 root, bytes32[] memory proof) = _head(0);
        bytes memory sigForTrail = _sign(WRITER_KEY, seq, entryHash, root);
        (bool ok,) = address(alc)
            .call(
                abi.encodeCall(
                    AnchoringLiveness.submit, (other, seq, entryHash, root, sigForTrail, proof)
                )
            );
        require(!ok, "a checkpoint signature was reusable across trails");
    }

    /// @notice Replaying an already-recorded head is refused; so is standing still.
    function test_seqMustStrictlyIncrease() public {
        _submitHead(0);
        _submitHead(1);
        (uint64 seq, bytes32 entryHash, bytes32 root, bytes32[] memory proof) = _head(0);
        bytes memory sig = _sign(WRITER_KEY, seq, entryHash, root);
        (bool ok, bytes memory err) = address(alc)
            .call(
                abi.encodeCall(AnchoringLiveness.submit, (TRAIL, seq, entryHash, root, sig, proof))
            );
        require(!ok, "an old head was replayed");
        require(bytes4(err) == AnchoringLiveness.SeqNotIncreasing.selector, "wrong reason");

        (seq, entryHash, root, proof) = _head(1);
        sig = _sign(WRITER_KEY, seq, entryHash, root);
        (ok, err) = address(alc)
            .call(
                abi.encodeCall(AnchoringLiveness.submit, (TRAIL, seq, entryHash, root, sig, proof))
            );
        require(!ok, "the current head was resubmitted");
        require(bytes4(err) == AnchoringLiveness.SeqNotIncreasing.selector, "wrong reason");
    }

    /// @notice THE GATE THAT MATTERS: a correctly signed head at a higher seq
    ///         is still refused if its tree does not contain the recorded one.
    /// @dev The proof supplied is not junk. It is the proof the rewriting
    ///      writer would honestly compute over its OWN forked tree -- valid
    ///      within that tree, worthless against the root this contract holds.
    ///      Without this gate a writer could rewrite history and keep
    ///      anchoring, and the seq check and the signature check would both
    ///      still pass.
    function test_rewrittenHistoryRejectedDespiteValidSignature() public {
        _submitHead(0);
        _submitHead(1);

        string memory json = _chunk("fork", 0);
        require(vm.parseJsonUint(json, _at(0, "oldSeq")) == 2, "fork vector expects head seq 2");
        uint64 seq = uint64(vm.parseJsonUint(json, _at(0, "seq")));
        bytes32 entryHash = vm.parseJsonBytes32(json, _at(0, "entryHash"));
        bytes32 root = vm.parseJsonBytes32(json, _at(0, "root"));
        bytes32[] memory proof = vm.parseJsonBytes32Array(json, _at(0, "proofFromPrev"));

        (bool ok, bytes memory err) = address(alc)
            .call(
                abi.encodeCall(
                    AnchoringLiveness.submit,
                    (TRAIL, seq, entryHash, root, _sign(WRITER_KEY, seq, entryHash, root), proof)
                )
            );
        require(!ok, "a rewritten trail advanced the on-chain head");
        require(bytes4(err) == AnchoringLiveness.NotAnExtension.selector, "wrong reason");
        // Custom-error data is a 4-byte selector followed by the ABI-encoded
        // arguments, so the selector has to be stripped before decoding.
        // Checking WHICH RFC 9162 reason came back is the point: "rejected"
        // and "rejected because the folded prefix root is not the recorded
        // one" are different claims, and only the second one says the trail
        // was rewritten.
        bytes memory args = new bytes(err.length - 4);
        for (uint256 i = 0; i < args.length; i++) {
            args[i] = err[i + 4];
        }
        Rfc9162.Fail reason = abi.decode(args, (Rfc9162.Fail));
        require(reason == Rfc9162.Fail.OldRootMismatch, "wrong RFC 9162 reason");

        (uint64 seenSeq,,,) = alc.lastSeen(TRAIL);
        require(seenSeq == 2, "the head moved on a rejected submit");
    }

    function test_delinquentAfterDeadline() public {
        _submitHead(0);
        vm.warp(block.timestamp + DEADLINE);
        require(!alc.isDelinquent(TRAIL), "delinquent exactly at the deadline");
        vm.warp(block.timestamp + 1);
        require(alc.isDelinquent(TRAIL), "not delinquent past the deadline");
        _submitHead(1);
        require(!alc.isDelinquent(TRAIL), "anchoring did not clear delinquency");
    }

    /// @notice A trail with nothing recorded is not "live".
    /// @dev `bool` is two-valued and the honest answer is three-valued: live,
    ///      delinquent, or nothing to judge. Reverting is what lets the
    ///      off-chain reader report `unreachable_or_absent` instead of
    ///      collapsing "never anchored" into the reassuring side of a binary
    ///      -- which is the beads v1.2.2 failure exactly.
    function test_absentTrailRevertsRatherThanReadingLive() public {
        bytes32 unregistered = keccak256("no-such-trail");
        (bool ok, bytes memory err) =
            address(alc).call(abi.encodeCall(AnchoringLiveness.isDelinquent, (unregistered)));
        require(!ok, "an unregistered trail returned a liveness verdict");
        require(bytes4(err) == AnchoringLiveness.TrailNotRegistered.selector, "wrong reason");

        (ok, err) = address(alc).call(abi.encodeCall(AnchoringLiveness.isDelinquent, (TRAIL)));
        require(!ok, "a registered trail with no head returned a liveness verdict");
        require(bytes4(err) == AnchoringLiveness.TrailNotRegistered.selector, "wrong reason");
    }

    /// @notice Registration is once-only: no writer rotation, no deadline change.
    /// @dev A mutable deadline would let a delinquent trail retroactively
    ///      redefine what "on time" meant; a mutable writer would let a
    ///      compromised key be laundered. Both are new trails, not edits.
    function test_registrationIsAppendOnly() public {
        (bool ok, bytes memory err) =
            address(alc).call(abi.encodeCall(AnchoringLiveness.registerTrail, (TRAIL, stranger, 1)));
        require(!ok, "a trail was re-registered");
        require(bytes4(err) == AnchoringLiveness.TrailAlreadyRegistered.selector, "wrong reason");
        require(alc.writerOf(TRAIL) == writer, "writer changed");
        require(alc.deadlineOf(TRAIL) == DEADLINE, "deadline changed");
    }

    function test_zeroWriterAndZeroDeadlineRejected() public {
        (bool ok, bytes memory err) = address(alc)
            .call(abi.encodeCall(AnchoringLiveness.registerTrail, (keccak256("a"), address(0), 1)));
        require(!ok && bytes4(err) == AnchoringLiveness.ZeroWriter.selector, "zero writer");
        (ok, err) = address(alc)
            .call(abi.encodeCall(AnchoringLiveness.registerTrail, (keccak256("b"), stranger, 0)));
        require(!ok && bytes4(err) == AnchoringLiveness.ZeroDeadline.selector, "zero deadline");
    }

    function test_submitToUnregisteredTrailRejected() public {
        (uint64 seq, bytes32 entryHash, bytes32 root, bytes32[] memory proof) = _head(0);
        (bool ok, bytes memory err) = address(alc)
            .call(
                abi.encodeCall(
                    AnchoringLiveness.submit,
                    (
                        keccak256("nope"),
                        seq,
                        entryHash,
                        root,
                        _sign(WRITER_KEY, seq, entryHash, root),
                        proof
                    )
                )
            );
        require(!ok, "submitted to an unregistered trail");
        require(bytes4(err) == AnchoringLiveness.TrailNotRegistered.selector, "wrong reason");
    }
}
