/* Compatibility barrel: callers keep importing from `@/lib/api`. */
export type {
  ApiKeyRecord,
  AuditReportJson,
  CadenceInput,
  Capabilities,
  ChainSummary,
  CheckSummaryJson,
  DeploymentSetting,
  DisplayEntry,
  EntryHeader,
  EntryPage,
  Head,
  ImportRecord,
  LedgerStatus,
  Meta,
  MintedKey,
  NewOperator,
  Operator,
  Outcome,
  OutcomeStatus,
  ReceiptHead,
  ReceiptRecord,
  ReceiptsCrossCheck,
  ReceiptsVerify,
  ReconcileOutcome,
  Reconciliation,
  ReportOutcome,
  RoleName,
  Scope,
  ServerSettings,
  SettingKind,
  StoredSetting,
  Verdict,
  Whoami,
  WitnessVerdictJson,
} from '../types/api'
export { ApiError, ENDPOINTS, api, buildEndpointPath } from '../api/client'
export type { EndpointAuth, EndpointDescriptor, HttpMethod } from '../api/client'
